// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Doc.Search.App.Models
{
    public partial class DocumentProperties
    {
        private string _blobType;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string BlobType
        {
            get { return this._blobType; }
            set { this._blobType = value; }
        }
        
        private string _container;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Container
        {
            get { return this._container; }
            set { this._container = value; }
        }
        
        private string _contentType;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ContentType
        {
            get { return this._contentType; }
            set { this._contentType = value; }
        }
        
        private int? _downloadsCounter;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? DownloadsCounter
        {
            get { return this._downloadsCounter; }
            set { this._downloadsCounter = value; }
        }
        
        private string _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ID
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private DateTimeOffset? _lastModified;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? LastModified
        {
            get { return this._lastModified; }
            set { this._lastModified = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        private double? _size;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? Size
        {
            get { return this._size; }
            set { this._size = value; }
        }
        
        private string _url;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Url
        {
            get { return this._url; }
            set { this._url = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the DocumentProperties class.
        /// </summary>
        public DocumentProperties()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken blobTypeValue = inputObject["blob_type"];
                if (blobTypeValue != null && blobTypeValue.Type != JTokenType.Null)
                {
                    this.BlobType = ((string)blobTypeValue);
                }
                JToken containerValue = inputObject["container"];
                if (containerValue != null && containerValue.Type != JTokenType.Null)
                {
                    this.Container = ((string)containerValue);
                }
                JToken contentTypeValue = inputObject["content_type"];
                if (contentTypeValue != null && contentTypeValue.Type != JTokenType.Null)
                {
                    this.ContentType = ((string)contentTypeValue);
                }
                JToken downloadsCounterValue = inputObject["downloads_counter"];
                if (downloadsCounterValue != null && downloadsCounterValue.Type != JTokenType.Null)
                {
                    this.DownloadsCounter = ((int)downloadsCounterValue);
                }
                JToken idValue = inputObject["id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.ID = ((string)idValue);
                }
                JToken lastModifiedValue = inputObject["last_modified"];
                if (lastModifiedValue != null && lastModifiedValue.Type != JTokenType.Null)
                {
                    this.LastModified = ((DateTimeOffset)lastModifiedValue);
                }
                JToken nameValue = inputObject["name"];
                if (nameValue != null && nameValue.Type != JTokenType.Null)
                {
                    this.Name = ((string)nameValue);
                }
                JToken sizeValue = inputObject["size"];
                if (sizeValue != null && sizeValue.Type != JTokenType.Null)
                {
                    this.Size = ((double)sizeValue);
                }
                JToken urlValue = inputObject["url"];
                if (urlValue != null && urlValue.Type != JTokenType.Null)
                {
                    this.Url = ((string)urlValue);
                }
            }
        }
    }
}
