// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Doc.Search.App;
using Doc.Search.App.Models;
using Microsoft.Rest;

namespace Doc.Search.App
{
    public static partial class IdentityOperationsExtensions
    {
        /// <param name='operations'>
        /// Reference to the Doc.Search.App.IIdentityOperations.
        /// </param>
        public static Identity Get(this IIdentityOperations operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IIdentityOperations)s).GetAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the Doc.Search.App.IIdentityOperations.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<Identity> GetAsync(this IIdentityOperations operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<Doc.Search.App.Models.Identity> result = await operations.GetWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
