// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Doc.Search.App.Models;
using Microsoft.Rest;

namespace Doc.Search.App
{
    public partial interface ISearchOperations
    {
        /// <param name='name'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<IList<DocumentProperties>>> SearchbyNameWithOperationResponseAsync(string name, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='viewsCounter'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> UpdateWithOperationResponseAsync(string id, int viewsCounter, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
